python_sources(name="service-lib", dependencies=["project-service:service-lib",
                                                "project-service:service_requires_dist",
                                                "project-models:model-lib"])

